# Generated by Django 5.1.2 on 2024-10-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(choices=[('parque', 'Parque público'), ('museu', 'Museu ou galeria de arte'), ('restaurante', 'Restaurante ou café'), ('hotel', 'Hotel ou hospedagem'), ('mercado', 'Supermercado ou feira')], default='parque', max_length=50),
        ),
    ]
