# Generated by Django 5.1.2 on 2024-10-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_lugar_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(choices=[('parque', 'Parque público'), ('museu', 'Museu ou galeria de arte'), ('restaurante', 'Restaurante ou café'), ('hotel', 'Hotel ou hospedagem'), ('mercado', 'Supermercado ou feira'), ('bike_reparo', 'Reparo de bicicleta')], default='parque', max_length=50),
        ),
    ]
