# Generated by Django 5.1.2 on 2024-10-22 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='estrelas',
            field=models.PositiveSmallIntegerField(default=2, help_text='Avaliação de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1, message='A avaliação deve ser de no mínimo 1 estrela.'), django.core.validators.MaxValueValidator(5, message='A avaliação pode ter no máximo 5 estrelas.')]),
            preserve_default=False,
        ),
    ]
