# Generated by Django 5.1.2 on 2024-10-22 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_comentario_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estrelas',
            field=models.PositiveSmallIntegerField(default=0, help_text='Avaliação de 0 a 5 estrelas', validators=[django.core.validators.MinValueValidator(0, message='A avaliação pode começar com 0 estrelas.'), django.core.validators.MaxValueValidator(5, message='A avaliação pode ter no máximo 5 estrelas.')]),
        ),
    ]
