# Generated by Django 5.1.2 on 2024-10-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_alter_comentario_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
