# Generated by Django 5.1.2 on 2024-10-22 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0008_alter_comentario_texto_avaliacaocomentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estrelas',
            field=models.PositiveSmallIntegerField(default=0, help_text='Avaliação de 0 a 5 estrelas', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
