# Generated by Django 5.1.2 on 2024-10-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_remove_comentario_estrelas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('responsavel', models.CharField(max_length=100)),
                ('contato', models.CharField(help_text='Email ou Telefone', max_length=100)),
                ('curtidas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
